;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.DebugDamage",DevComment="")
+GameplayTagList=(Tag="Data.Biome.TestGrasslands",DevComment="")
+GameplayTagList=(Tag="Data.Biome.TestGrasslands.Dirt",DevComment="")
+GameplayTagList=(Tag="Data.TileSet.TestGrass",DevComment="")
+GameplayTagList=(Tag="Data.TileSet.TestGrass.Dirt",DevComment="")
+GameplayTagList=(Tag="Effect.DebugDamage",DevComment="for debug purposes")

